apiVersion: v1
kind: Service
metadata:
  name: nodejs-consumer
  labels:
    app: nodejs
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: nodejs-1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-consumer
  labels:
    app: nodejs-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-1
  template:
    metadata:
      labels:
        app: nodejs-1
    spec:
      containers:
        - name: node-server-1
          image: node-server-1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000