apiVersion: v1
kind: Service
metadata:
  name: nodejs-consumer
  labels:
    app: nodejs
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: presentation-layer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-consumer
  labels:
    app: presentation-layer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: presentation-layer
  template:
    metadata:
      labels:
        app: presentation-layer
    spec:
      containers:
        - name: presentation-layer
          image: presentation-layer
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
